logo: /assets/images/profile.gif
title: KARAN PANDEY
description: (PMP速 | PRINCE2 Agile速 Practitioner | ITIL速 | CSM速 | ACCP)
show_downloads: /assets/images/profile.gif
google_analytics:
theme: jekyll-theme-architect
